Vagrant.configure("2") do |config|
  config.vm.box = "generic/oracle8"
  config.vm.hostname = "jenkins"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8091, host: 8091
  config.vm.network "private_network", ip: "192.168.1.5"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory=2048
  end
  # comandos que não estão no curso
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
end