Vagrant.configure("2") do |config|
    config.vm.box = "generic/oracle8"
    config.vm.hostname = "app01"
    config.vm.network "private_network", ip: "192.168.1.3"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "shell", path: "provision.sh"
  
    # comandos que não estão no curso
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
  end