Vagrant.configure("2") do |config|
  config.vm.box = "generic/oracle8"
  config.vm.hostname = "sonarqube"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory=1024
  end
  # comandos que não estão no curso
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
end