Vagrant.configure("2") do |config|
  config.vm.box = "generic/oracle8"
  config.vm.hostname = "manager"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.provider "virtualbox" do |v|
    v.memory=2048
  end
  # comandos que não estão no curso
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
end